### ISSUE TITLE
Remove dconf workaround

### ISSUE THREAD

**Issue by eszlari** [flathub/io.github.quodlibet.QuodLibet#16]
https://blogs.gnome.org/mclasen/2019/07/12/settings-in-a-sandbox-world/

**Comment by lazka** [comment]
Does this work with older distro versions?

**Comment by eszlari** [comment]
AFAIK only needs freedesktop runtime >=19.08

**Comment by lazka** [comment]
I mean the portal on the host

**Comment by eszlari** [comment]
AFAIK it has nothing to do with the portal. The fix/change is in glib, makes it store all settings in `~.var/app/$ID`.

**Comment by lazka** [comment]
> For shared desktop-wide settings, there is a companion Settings portal, which provides readonly access to some global settings. It is used transparently by GTK and Qt for toolkit-level settings.

I assume if the portal isn't there, then the app can't read those global settings.

**Comment by 0rzech** [comment]
It looks like the the settings portal has been there since late 2018 (flatpak/xdg-desktop-portal#245) with some possibly important commit in late 2019 (flatpak/xdg-desktop-portal#407). If I understand https://gitlab.gnome.org/GNOME/glib/-/issues/2213 right, GSettings does not use settings portal underneath and one has to use the portal directly with the caveat of not all settings being readable, but perhaps Quod Libet uses things already available through GUI toolkits and other portals?

**Comment by lazka** [comment]
thanks, let's assume it has been long enough and things work for most users now.

If anyone finds any regressions that could potentially be caused by this then please open an issue.
